@baseUrl=http://localhost:3000/api
@resourceName=products

# Products

# @name getAll
GET {{baseUrl}}/{{resourceName}}

###

# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?price_gte=900

###

# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?name_like=tasty


###

# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=1&_limit=20

###

# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=desc


###

# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
  "categoryId": "28759f7e-3509-4064-920a-406dd426033a",
  "name": "Tasty Plastic Chips",
  "color": "cyan",
  "price": 931,
  "description": "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
  "thumbnailUrl": "http://placeimg.com/400/400"
}

###

# @name update
PATCH {{baseUrl}}/{{resourceName}}/KkSXxPt
Content-Type: application/json

{
  "name": "Tasty Plastic Chips Update",
  "color": "red",
  "price": 950
}

###

# @name remove
DELETE {{baseUrl}}/{{resourceName}}/2
